/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Milisto (https://sketchfab.com/Milisto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-room-ac1f66c55e234591b78c721150e99f35
Title: Isometric Room
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import roomScene from '../assets/3d/isometric_room.glb'
const Room = (props) => {
  const islandRef = useRef();  
  const { nodes, materials } = useGLTF(roomScene);
  return (
    <a.group ref = { islandRef } {...props} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.456}>
        <lineSegments
          geometry={nodes.Object_2.geometry}
          material={materials.AMPL3}
        />
        <mesh
          
          
          geometry={nodes.Object_3.geometry}
          material={materials.material}
        />
        <mesh
          
          
          geometry={nodes.Object_4.geometry}
          material={materials.Carpet}
        />
        <lineSegments
          geometry={nodes.Object_5.geometry}
          material={materials.Chair}
        />
        <mesh
          
          
          geometry={nodes.Object_6.geometry}
          material={materials.Chords}
        />
        <mesh
          
          
          geometry={nodes.Object_7.geometry}
          material={materials.Floor}
        />
        <mesh
          
          
          geometry={nodes.Object_8.geometry}
          material={materials.Manico}
        />
        <mesh
          
          
          geometry={nodes.Object_9.geometry}
          material={materials.Material}
        />
        <mesh
          
          
          geometry={nodes.Object_10.geometry}
          material={materials["Material.003dwd"]}
        />
        <mesh
          
          
          geometry={nodes.Object_11.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          
          
          geometry={nodes.Object_12.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          
          
          geometry={nodes.Object_13.geometry}
          material={materials.material_25}
        />
        <mesh
          
          
          geometry={nodes.Object_14.geometry}
          material={materials.Pedal}
        />
        <mesh
          
          
          geometry={nodes.Object_15.geometry}
          material={materials.Pedal_2}
        />
        <mesh
          
          
          geometry={nodes.Object_16.geometry}
          material={materials.Pedal_3}
        />
        <mesh
          
          
          geometry={nodes.Object_17.geometry}
          material={materials.Piano}
        />
        <mesh
          
          
          geometry={nodes.Object_18.geometry}
          material={materials.Queen}
        />
        <mesh
          
          
          geometry={nodes.Object_19.geometry}
          material={materials.Sill_material}
        />
        <mesh
          
          
          geometry={nodes.Object_20.geometry}
          material={materials.Socket}
        />
        <mesh
          
          
          geometry={nodes.Object_21.geometry}
          material={materials.White}
        />
        <mesh
          
          
          geometry={nodes.Object_22.geometry}
          material={materials.beatles}
        />
        <mesh
          
          
          geometry={nodes.Object_23.geometry}
          material={materials.bucket_2}
        />
        <mesh
          
          
          geometry={nodes.Object_24.geometry}
          material={materials.hidden_material}
        />
        <lineSegments
          geometry={nodes.Object_25.geometry}
          material={materials.microphone2}
        />
        <mesh
          
          
          geometry={nodes.Object_26.geometry}
          material={materials.material_51}
        />
        <mesh
          
          
          geometry={nodes.Object_27.geometry}
          material={materials.AMPL3}
        />
        <mesh
          
          
          geometry={nodes.Object_28.geometry}
          material={materials.Asta}
        />
        <mesh
          
          
          geometry={nodes.Object_29.geometry}
          material={materials.Bridge}
        />
        <mesh
          
          
          geometry={nodes.Object_30.geometry}
          material={materials.Chair}
        />
        <mesh
          
          
          geometry={nodes.Object_31.geometry}
          material={materials.Chitarra}
        />
        <mesh
          
          
          geometry={nodes.Object_32.geometry}
          material={materials.Cuscino}
        />
        <mesh
          
          
          geometry={nodes.Object_33.geometry}
          material={materials.Desk}
        />
        <mesh
          
          
          geometry={nodes.Object_34.geometry}
          material={materials.Glass_material}
        />
        <mesh
          
          
          geometry={nodes.Object_35.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          
          
          geometry={nodes.Object_36.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          
          
          geometry={nodes.Object_37.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          
          
          geometry={nodes.Object_38.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          
          
          geometry={nodes.Object_39.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          
          
          geometry={nodes.Object_40.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          
          
          geometry={nodes.Object_41.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          
          
          geometry={nodes.Object_42.geometry}
          material={materials.None}
        />
        <mesh
          
          
          geometry={nodes.Object_43.geometry}
          material={materials.Pedal_4}
        />
        <mesh
          
          
          geometry={nodes.Object_44.geometry}
          material={materials.Plastic_Handle_material}
        />
        <mesh
          
          
          geometry={nodes.Object_45.geometry}
          material={materials.Speaker}
        />
        <mesh
          
          
          geometry={nodes.Object_46.geometry}
          material={materials.Window_material}
        />
        <mesh
          
          
          geometry={nodes.Object_47.geometry}
          material={materials.ampl1}
        />
        <mesh
          
          
          geometry={nodes.Object_48.geometry}
          material={materials.ampl2}
        />
        <mesh
          
          
          geometry={nodes.Object_49.geometry}
          material={materials.bucket}
        />
        <mesh
          
          
          geometry={nodes.Object_50.geometry}
          material={materials.bucket}
        />
        <mesh
          
          
          geometry={nodes.Object_51.geometry}
          material={materials.button}
        />
        <mesh
          
          
          geometry={nodes.Object_52.geometry}
          material={materials.front_chair}
        />
        <mesh
          
          
          geometry={nodes.Object_53.geometry}
          material={materials.microphone}
        />
        <mesh
          
          
          geometry={nodes.Object_54.geometry}
          material={materials.microphone2}
        />
        <mesh
          
          
          geometry={nodes.Object_55.geometry}
          material={materials.node}
        />
        <mesh
          
          
          geometry={nodes.Object_56.geometry}
          material={materials.node}
        />
        <mesh
          
          
          geometry={nodes.Object_57.geometry}
          material={materials.socket_c}
        />
        <mesh
          
          
          geometry={nodes.Object_58.geometry}
          material={materials.sofa}
        />
      </group>
    </a.group>
  );
}


export default Room;